"""Local browser dashboard for GameClip Publisher."""
from fastapi.responses import HTMLResponse


def dashboard():
    return HTMLResponse(r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0b1018"><title>GameClip Publisher</title>
<style>
:root{color-scheme:dark;--bg:#0b1018;--card:#141c27;--line:#263244;--muted:#9aabc0;--blue:#3478f6;--green:#37c995;--red:#ff7c83}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f4f7fb;font:15px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer}.wrap{max-width:1100px;margin:auto;padding:25px 22px 64px}.head{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.brand{font-weight:900;font-size:24px;letter-spacing:.04em}.sub,.muted{color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px;margin-top:18px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:25px 0}.tab,.secondary{color:#eaf1fa;background:#1a2533;border:1px solid #2c3b50;border-radius:10px;padding:10px 14px}.tab.active,.primary{background:var(--blue);border-color:var(--blue);color:#fff}.primary{border:0;border-radius:10px;padding:12px 17px;font-weight:750}.danger{background:#49232b;color:#ffe2e5;border:1px solid #683640;border-radius:9px;padding:8px 12px}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.field{display:flex;flex-direction:column;gap:6px}.field.full{grid-column:1/-1}label{font-size:13px;color:#c7d3e2;font-weight:700}input,textarea,select{width:100%;color:#f5f8fc;background:#0f1620;border:1px solid #2b394c;border-radius:9px;padding:11px 12px}textarea{min-height:100px;resize:vertical}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.check{display:flex;align-items:center;gap:8px;background:#101824;border:1px solid var(--line);border-radius:10px;padding:10px}.check input{width:auto}.note{color:var(--muted);font-size:14px;margin:12px 0 0}.status{padding:12px 14px;border-radius:10px;background:#14261f;color:#a8f3d5;margin-top:14px}.error{background:#321c23;color:#ffc3c9}.progress{height:10px;background:#273344;border-radius:99px;overflow:hidden;margin:14px 0}.bar{height:100%;width:0;background:var(--green);transition:width .3s}.list{display:grid;gap:10px;margin-top:14px}.item{display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap;padding:13px 15px;border:1px solid var(--line);border-radius:11px;background:#101721}.item small{display:block;color:var(--muted)}.right{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.hidden{display:none!important}.pill{font-size:12px;color:#cce0ff;background:#1c2b40;border-radius:20px;padding:4px 9px}.warn{color:#ffd995}.empty{padding:18px;color:var(--muted);text-align:center}.keybox{max-width:520px;margin:50px auto}.footer{color:#66768c;font-size:12px;margin-top:40px}
@media(max-width:650px){.wrap{padding:18px 13px 45px}.fields{grid-template-columns:1fr}.field.full{grid-column:auto}.brand{font-size:20px}.card{padding:16px}}
</style></head>
<body><main class="wrap">
<header class="head"><div><div class="brand">GAMECLIP PUBLISHER</div><div class="sub">Create clips · Connect accounts · Schedule uploads</div></div><div class="right"><span class="pill" id="serverLabel"></span><button class="secondary hidden" id="logout">Lock</button></div></header>
<section class="card keybox" id="login">
 <h1>Connect to your server</h1><p class="muted">Enter the GAMECLIP_API_KEY from the server’s private .env file. The key stays in this browser tab and is not saved.</p>
 <div class="field"><label for="accessKey">Server access key</label><input id="accessKey" type="password" autocomplete="off" placeholder="GAMECLIP_API_KEY"></div>
 <button class="primary" id="connect" style="margin-top:14px">Connect</button><div id="loginMessage" class="note"></div>
</section>
<section id="app" class="hidden">
 <nav class="tabs"><button class="tab active" data-tab="create">Create clips</button><button class="tab" data-tab="clips">Clip library</button><button class="tab" data-tab="schedule">Schedule</button><button class="tab" data-tab="accounts">Accounts</button></nav>
 <section class="page" id="page-create">
  <div class="card"><h1>Create clips</h1><p class="note">Choose a source video. The computer sends it to this server and analyzes selected sections in sequential 10-minute batches. The source file on your computer is left untouched.</p>
   <div class="fields" style="margin-top:18px"><div class="field full"><label for="video">Gameplay video (up to 2 GiB by default)</label><input id="video" type="file" accept="video/*"></div>
    <div class="field"><label for="clipCount">Number of clips</label><select id="clipCount"><option>3</option><option selected>6</option><option>10</option><option>15</option></select></div>
    <div class="field"><label for="clipLength">Clip length</label><select id="clipLength"><option value="15">15 seconds</option><option value="30" selected>30 seconds</option><option value="45">45 seconds</option><option value="60">60 seconds</option></select></div>
    <label class="check"><input id="vertical" type="checkbox" checked> Portrait 9:16 output</label>
   </div><button class="primary" id="create" style="margin-top:16px">Upload and create clips</button><div id="uploadProgress" class="hidden"><div class="progress"><div class="bar" id="bar"></div></div><div id="progressText" class="note"></div></div><div id="createMessage" class="note"></div>
  </div>
 </section>
 <section class="page hidden" id="page-clips"><div class="card"><div class="head"><h1>Clip library</h1><button class="secondary" id="refreshLibrary">Refresh</button></div><p class="note">Clips are kept on the server. Download a clip here or select it in Schedule.</p><div id="library" class="list"></div></div></section>
 <section class="page hidden" id="page-schedule"><div class="card"><h1>Schedule uploads</h1><div id="schedulerStatus" class="note"></div><div class="fields" style="margin-top:16px">
  <div class="field full"><label>Choose clips</label><div id="scheduleClips" class="list"></div></div>
  <div class="field full"><label>Connected platforms</label><div id="schedulePlatforms" class="row"></div></div>
  <div class="field"><label for="title">Title</label><input id="title" maxlength="100" placeholder="Video title"></div>
  <div class="field"><label for="firstAt">First upload time (your local time)</label><input id="firstAt" type="datetime-local"></div>
  <div class="field full"><label for="caption">Caption / description</label><textarea id="caption" maxlength="2200" placeholder="Description, hashtags, links"></textarea></div>
  <div class="field"><label for="interval">Hours between clips</label><input id="interval" type="number" min="1" max="168" value="3"></div>
  <div class="field"><label for="privacy">YouTube visibility</label><select id="privacy"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select></div>
  <label class="check"><input id="kids" type="checkbox"> Made for kids</label>
 </div><p class="note">Titles, captions and settings are sent automatically where a platform supports them. TikTok inbox drafts still need their caption and final publishing completed in TikTok.</p><button class="primary" id="schedule" style="margin-top:16px">Review and schedule</button><div id="scheduleMessage" class="note"></div></div>
 <div class="card"><div class="head"><h2>Publishing queue</h2><button class="secondary" id="refreshQueue">Refresh</button></div><div id="queue" class="list"></div></div></section>
 <section class="page hidden" id="page-accounts"><div class="card"><div class="head"><h1>Social accounts</h1><button class="secondary" id="refreshAccounts">Refresh</button></div><p class="note">Connect or manage the accounts configured on your backend.</p><div id="accounts" class="list"></div></div></section>
</section><div class="footer">GameClip Publisher runs on your own server. Keep your computer, server process and Tailscale Funnel running for scheduled jobs.</div>
</main>
<script>
(()=>{
let apiKey='';let social={platforms:[]};let library=[];let queue=[];let lastClips=[];
const $=id=>document.getElementById(id);
const setMessage=(id,text,error=false)=>{$(id).textContent=text;$(id).classList.toggle('error',error)};
async function request(path,method='GET',body){const r=await fetch(path,{method,headers:{'X-API-Key':apiKey,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});let j;try{j=await r.json()}catch{throw new Error('Server returned an unreadable response.')}if(!r.ok)throw new Error(typeof j.detail==='string'?j.detail:`Server returned ${r.status}.`);return j}
function showApp(){ $('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('serverLabel').textContent=location.host;refreshAll();}
async function login(){apiKey=$('accessKey').value.trim();if(!apiKey){setMessage('loginMessage','Enter your server access key.',true);return}try{social=await request('/api/social');showApp()}catch(e){apiKey='';setMessage('loginMessage',e.message,true)}}
function activate(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('hidden',p.id!=='page-'+name));if(name==='clips'||name==='schedule')loadLibrary();if(name==='accounts')loadAccounts();if(name==='schedule')loadQueue()}
async function refreshAll(){await Promise.allSettled([loadAccounts(),loadLibrary(),loadQueue()])}
async function loadLibrary(){try{library=await request('/api/library');renderLibrary();renderScheduleClips()}catch(e){$('library').textContent=e.message}}
function renderLibrary(){const root=$('library');root.replaceChildren();if(!library.length){root.innerHTML='<div class="empty">No clips yet. Create some in the Create clips tab.</div>';return}library.forEach(c=>{const row=document.createElement('div');row.className='item';const left=document.createElement('div');left.textContent=c.name;const right=document.createElement('div');right.className='right';const date=document.createElement('small');date.textContent=new Date(c.created*1000).toLocaleString();const btn=document.createElement('button');btn.className='secondary';btn.textContent='Download';btn.onclick=()=>downloadClip(c);right.append(date,btn);row.append(left,right);root.append(row)})}
function renderScheduleClips(){const root=$('scheduleClips');root.replaceChildren();if(!library.length){root.innerHTML='<div class="empty">Create clips first. Scheduling requires persistent server storage.</div>';return}library.forEach(c=>{const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.value=c.id;const span=document.createElement('span');span.textContent=c.name;label.append(input,span);root.append(label)})}
async function downloadClip(c){try{const r=await fetch(c.download_path,{headers:{'X-API-Key':apiKey}});if(!r.ok)throw new Error('Could not download this clip.');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=c.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}catch(e){alert(e.message)}}
async function createClips(){const file=$('video').files[0];if(!file){setMessage('createMessage','Choose a video first.',true);return}if(file.size>2*1024*1024*1024){setMessage('createMessage','This file is above the default 2 GiB limit. Increase MAX_VIDEO_UPLOAD_BYTES on the server.',true);return}const btn=$('create');btn.disabled=true;$('uploadProgress').classList.remove('hidden');$('bar').style.width='0%';setMessage('createMessage','Uploading source video…');const form=new FormData();form.append('video',file,file.name);form.append('clip_count',$('clipCount').value);form.append('clip_duration',$('clipLength').value);form.append('vertical',String($('vertical').checked));
 try{const job=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/create-clips');xhr.setRequestHeader('X-API-Key',apiKey);xhr.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.round(e.loaded/e.total*100);$('bar').style.width=p+'%';$('progressText').textContent=`Uploading video… ${p}%`}};xhr.onerror=()=>reject(new Error('Upload connection failed. Check that the server is running and try again.'));xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(new Error(`Server returned ${xhr.status}.`));return}if(xhr.status<200||xhr.status>=300){reject(new Error(data.detail||`Server returned ${xhr.status}.`));return}resolve(data)};xhr.send(form)});if(!job.job_id)throw new Error('The server did not return a processing job ID. Update the backend.');setMessage('createMessage','Upload complete. Analyzing 10-minute batches on your computer…');let result;while(true){await new Promise(r=>setTimeout(r,2500));const state=await request('/api/create-clips/'+encodeURIComponent(job.job_id));$('bar').style.width=Math.round((state.progress||0)*100)+'%';$('progressText').textContent=state.message||'Processing…';if(state.status==='completed'){result=state;break}if(state.status==='failed')throw new Error(state.message||'Video processing failed.')}lastClips=result.clips||[];await loadLibrary();setMessage('createMessage',`${lastClips.length} clips created. Find them in Clip library or Schedule.`);$('video').value='';activate('clips')}catch(e){setMessage('createMessage',e.message,true)}finally{btn.disabled=false}}
async function loadAccounts(){try{social=await request('/api/social');const root=$('accounts');root.replaceChildren();social.platforms.forEach(p=>{const row=document.createElement('div');row.className='item';const left=document.createElement('div');left.textContent=p.platform.toUpperCase()+' · '+(p.connected?'Connected':'Not connected');const hint=document.createElement('small');hint.textContent=p.label||p.reason||p.mode||'';left.append(hint);const actions=document.createElement('div');actions.className='right';if(p.platform==='instagram'||p.platform==='facebook'){const sel=document.createElement('button');sel.className='secondary';sel.textContent='Select account';sel.onclick=()=>selectAccount(p.platform);actions.append(sel)}const btn=document.createElement('button');btn.className='primary';btn.textContent=p.connected?'Reconnect':'Connect';btn.disabled=!p.configured;btn.onclick=()=>connectAccount(p.platform);actions.append(btn);if(p.connected){const del=document.createElement('button');del.className='danger';del.textContent='Disconnect';del.onclick=()=>disconnectAccount(p.platform);actions.append(del)}row.append(left,actions);root.append(row)});const state=$('schedulerStatus');state.textContent=social.durable_storage&&social.scheduler_enabled?'Persistent storage and automatic scheduler are enabled.':!social.durable_storage?'Scheduling is off: enable persistent storage on the server.':'Scheduling is off: set SCHEDULER_ENABLED=true and restart the server.';state.classList.toggle('warn',!social.durable_storage||!social.scheduler_enabled);renderSchedulePlatforms()}catch(e){$('accounts').textContent=e.message}}
function renderSchedulePlatforms(){const root=$('schedulePlatforms');root.replaceChildren();social.platforms.filter(p=>p.connected).forEach(p=>{const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.value=p.platform;const span=document.createElement('span');span.textContent=p.platform;label.append(input,span);root.append(label)});if(!root.childElementCount)root.textContent='Connect an account first.'}
async function connectAccount(p){try{const result=await request('/api/social/'+p+'/connect','POST');window.open(result.url,'_blank','noopener,noreferrer')}catch(e){alert(e.message)}}
async function disconnectAccount(p){if(!confirm(`Disconnect ${p} and cancel its queued uploads?`))return;try{await request('/api/social/'+p,'DELETE');await loadAccounts();await loadQueue()}catch(e){alert(e.message)}}
async function selectAccount(p){try{const choices=await request('/api/social/'+p+'/choices');if(!choices.length)throw new Error('No eligible accounts found.');const labels=choices.map((c,i)=>`${i+1}. ${c.instagram?.username||c.name}`).join('\n');const answer=prompt('Choose a number:\n'+labels);if(!answer)return;const c=choices[Number(answer)-1];if(!c)throw new Error('Choose a number from the list.');await request('/api/social/'+p+'/select','POST',{page_id:c.id});await loadAccounts()}catch(e){alert(e.message)}}
async function loadQueue(){try{queue=await request('/api/queue');const root=$('queue');root.replaceChildren();if(!queue.length){root.innerHTML='<div class="empty">No scheduled uploads yet.</div>';return}queue.forEach(j=>{const row=document.createElement('div');row.className='item';const left=document.createElement('div');left.textContent=`${j.name} → ${j.platform}`;const details=document.createElement('small');details.textContent=`${new Date(j.due*1000).toLocaleString()} · ${j.status}${j.error?' · '+j.error:''}${j.status==='awaiting_user'?' · Open TikTok inbox to finish posting.':''}`;left.append(details);row.append(left);if(j.status==='queued'){const cancel=document.createElement('button');cancel.className='danger';cancel.textContent='Cancel';cancel.onclick=async()=>{try{await request('/api/queue/'+j.id,'DELETE');await loadQueue()}catch(e){alert(e.message)}};row.append(cancel)}root.append(row)})}catch(e){$('queue').textContent=e.message}}
async function schedule(){try{const clip_ids=[...document.querySelectorAll('#scheduleClips input:checked')].map(x=>x.value);const platforms=[...document.querySelectorAll('#schedulePlatforms input:checked')].map(x=>x.value);const title=$('title').value.trim();const local=$('firstAt').value;if(!clip_ids.length||!platforms.length||!title||!local)throw new Error('Choose clips, platforms, a title and a first upload time.');const when=new Date(local);if(when<=new Date())throw new Error('Choose a future upload time.');const interval=Number($('interval').value);if(!Number.isInteger(interval)||interval<1||interval>168)throw new Error('Set the interval from 1 to 168 hours.');const body={clip_ids,platforms,title,caption:$('caption').value,first_at:when.toISOString(),interval_hours:interval,youtube_privacy:$('privacy').value,made_for_kids:$('kids').checked,consent:true};if(!confirm(`Schedule ${clip_ids.length} clips to ${platforms.join(', ')} starting ${when.toLocaleString()}? Title, caption and supported settings will be used automatically. TikTok sends drafts for you to finish in TikTok.`))return;await request('/api/queue','POST',body);setMessage('scheduleMessage','Scheduled. Your computer will upload each item when it is due.');await loadQueue()}catch(e){setMessage('scheduleMessage',e.message,true)}}
$('connect').onclick=login;$('accessKey').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=()=>{apiKey='';$('app').classList.add('hidden');$('logout').classList.add('hidden');$('login').classList.remove('hidden');$('accessKey').value=''};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>activate(b.dataset.tab));$('create').onclick=createClips;$('refreshLibrary').onclick=loadLibrary;$('refreshQueue').onclick=loadQueue;$('refreshAccounts').onclick=loadAccounts;$('schedule').onclick=schedule;
const initial=new Date(Date.now()+3600000);initial.setMinutes(initial.getMinutes()-initial.getTimezoneOffset());$('firstAt').value=initial.toISOString().slice(0,16);
})();
</script></body></html>''')
